# Generated by Django 5.0.6 on 2024-06-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelis')),
                ('description', models.TextField(max_length=1000, verbose_name='Aprašymas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioners', to='catalog.country', verbose_name='Šalis')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioners', to='catalog.manufacturer', verbose_name='Gamintojas')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_unit_dimensions', models.CharField(max_length=50, verbose_name='Vidinio bloko matmenys')),
                ('outdoor_unit_dimensions', models.CharField(max_length=50, verbose_name='Išorinio bloko matmenys')),
                ('power', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Galingumas (kW)')),
                ('energy_efficiency_class', models.CharField(max_length=10, verbose_name='Energijos efektyvumo klasė')),
                ('operating_temperature', models.CharField(max_length=50, verbose_name='Darbinės temperatūros ribos šaldymas/šildymas')),
                ('outdoor_unit_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Svoris išorinio bloko (kg)')),
                ('indoor_unit_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Svoris vidinio bloko (kg)')),
                ('air_conditioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specification', to='catalog.airconditioner', verbose_name='Oro kondicionierius')),
            ],
        ),
    ]

