# Generated by Django 5.0.6 on 2024-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_airconditioner_technicalspecification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditioner',
            options={'verbose_name': 'Oro Kondicionierius', 'verbose_name_plural': 'Oro Kondicionieriai'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Šalis', 'verbose_name_plural': 'Šalys'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Gamintojas', 'verbose_name_plural': 'Gamintojai'},
        ),
        migrations.AlterModelOptions(
            name='technicalspecification',
            options={'verbose_name': 'Techninė specifikaciją', 'verbose_name_plural': 'Techninės specifikacijos'},
        ),
        migrations.RemoveField(
            model_name='technicalspecification',
            name='power',
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Galingumas (kW)'),
        ),
    ]
