# Generated by Django 5.0.6 on 2024-07-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_airconditioner_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Aprašymas'),
        ),
    ]
