# Generated by Django 5.0.6 on 2024-07-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_airconditioner_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalspecification',
            name='air_conditioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='catalog.airconditioner', verbose_name='Oro kondicionierius'),
        ),
    ]
