# Generated by Django 5.0.6 on 2024-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_technicalspecification_air_conditioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Logotipas'),
        ),
    ]
