# Generated by Django 5.0.6 on 2024-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_airconditioner_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalspecification',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Nuotrauka'),
        ),
    ]
