# Generated by Django 5.0.6 on 2024-07-10 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_technicalspecification_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('content', models.TextField(max_length=5000, verbose_name='Užsakymas')),
                ('air_conditioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.technicalspecification', verbose_name='Techninė specifikacija')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'ordering': ['-date_created'],
            },
        ),
    ]
