# Generated by Django 5.0.6 on 2024-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
